velib_demand:
  target: prod
  outputs:
    prod:
      type: postgres
      host: "{{env_var('PGHOST')}}"
      port: "{{env_var('PGPORT') | int}}"
      user: "{{env_var('PGUSER')}}"
      password: "{{env_var('PGPASSWORD')}}"
      dbname: "{{env_var('PGDATABASE')}}"
      schema: silver
      threads: 4