# NE PAS committer avec de vraies valeurs.
# Créer à la main avec kubectl (voir README).
apiVersion: v1
kind: Secret
metadata:
  name: velib-postgres-credentials
  namespace: user-fabienhos
type: Opaque
stringData:
  PGHOST: postgresql-cnpg-114514-rw
  PGPORT: "5432"
  PGDATABASE: defaultdb
  PGUSER: <utilisateur>
  PGPASSWORD: <mot-de-passe>
