[project]
name = "velib-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "surybang", email = "hos.fabien@outlook.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.141.1",
    "psycopg2-binary>=2.9.12",
    "pydantic-settings>=2.15.0",
    "uvicorn>=0.52.4",
]

[project.scripts]
velib-api = "velib_api:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=9.1.1",
    "ruff>=0.16.6",
]
